# Generated by Django 5.1.6 on 2025-03-01 20:41

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contest_end_datetime_and_more_squashed_0003_remove_contest_datetime_range_contest_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.Solution.get_filename),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File'), ('choice', 'Choice')], max_length=16),
        ),
        migrations.DeleteModel(
            name='SolutionFile',
        ),
    ]
