# Generated by Django 5.1.6 on 2025-03-02 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solution_file_solution_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='cross_check_org_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrgVerdict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='api.solution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
