# Generated by Django 5.1.6 on 2025-03-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contest_cross_check_org_count_solution_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='choices',
            field=models.JSONField(null=True),
        ),
    ]
