# Generated by Django 5.1.6 on 2025-03-03 09:10

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=api.models.User.get_filename),
        ),
        migrations.AlterField(
            model_name='orgverdict',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий организатор'),
        ),
        migrations.AlterField(
            model_name='orgverdict',
            name='points',
            field=models.PositiveIntegerField(verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='orgverdict',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', related_query_name='verdict', to='api.solution', verbose_name='Решение'),
        ),
    ]
